include ../../Makefile.common

DEBPKG_NAME:=codesourcery-ia32-2011.09.deb
DEB_REPO:=oneiric

.PHONY: deb-pkg all

all:
	@echo "target deb-pkg..."

${DEBPKG_NAME}:
	fakeroot dpkg-deb --build debian $@

repo: ${DEBPKG_NAME}
	dpkg-sig -k ${GPG_KEY} --sign builder $<
	sudo reprepro --basedir /var/www/repos/apt/ubuntu includedeb ${DEB_REPO} $<
	rm -f $<


install:
	find  .. -maxdepth 1 -executable -type f -exec ln -s {} . \;
