install:
	npm install -g #--prefix=$HOME/lophilo-bin

debpkg:
	mkdir -p ./debian/usr/lib/node_modules/lophilo
	cp ../lophilo-node/lophilo.js ../lophilo-node/lophilo
	cp ../lophilo-node/lophilo.js ../lophilo-node/package.json ./debian/usr/lib/node_modules/lophilo
