LOPHILO_TARGET_ARCH:=arm
include ../Makefile.common

export PATH:=${TOOLCHAIN_PATH}:${PATH}
export CROSS_COMPILE:=""

all:
	which gcc

build:
	make -C board/at91sam9m10ekes/dataflash rebuild

clean:
	make -C board/at91sam9m10ekes/dataflash clean
