include ../Makefile.common

ifeq ($(LOPHILO_TARGET_ARCH),arm)
	CONFIGURE_TARGET:=linux-armv4
else
	CONFIGURE_TARGET:=linux-elf
endif

.PHONY: config build

config:
	./Configure ${CONFIGURE_TARGET}

build:
	make -j8
