export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabi-
export TODAY:=$(shell date +%Y%m%d)
export VERSION:=$(shell make -s -C ${KBUILD_SRC} kernelversion)
export IMAGE:=bin/busybox

.PHONY: clean config menuconfig test backup

menuconfig:
	make menuconfig

busybox: ${IMAGE}

${IMAGE}: Makefile
	time make defconfig
	time make

version:
	make kernelversion

clean:
	make clean
