include ../../Makefile.common

DEBPKG_NAME:=codesourcery-arm-2011.09.deb

.PHONY: deb-pkg all install repo

all:
	@echo "target deb-pkg..."

debpkg:
	fakeroot dpkg-deb --build debian ${DEBPKG_NAME}

repo:
	dpkg-sig -k ${GPG_KEY} --sign builder ${DEBPKG_NAME}
	sudo reprepro --basedir /var/www/repos/apt/${DEB_REPO} includedeb ${DEB_CODENAME} ${DEBPKG_NAME}

install:
	find  .. -maxdepth 1 -executable -type f -exec ln -s {} . \;
